name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Restore Go modules cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.23-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.23-
    
    - name: Clean Go toolchain cache conflicts
      run: |
        # Remove any conflicting toolchain files from cache
        find ~/go/pkg/mod -name "golang.org" -type d -exec rm -rf {} + 2>/dev/null || true
      continue-on-error: true
    
    - name: Download dependencies
      run: go mod tidy
    
    - name: Run tests
      run: make test
    
    - name: Test build all platforms
      run: make build-all
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/
        retention-days: 7
    
    - name: Save Go modules cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.23-${{ hashFiles('**/go.sum') }}